export const buttonStyles = ({
  position: "relative",
  display: "inline-block",
  padding: "10px 20px",
  color: "#03e9f4",
  fontSize: 16,
  textDecoration: "none",
  textTransform: "uppercase",
  overflow: "hidden",
  transition: "0.5s",
  marginTop: 4,
  letterSpacing: 4,
  "&:hover": {
    background: "#03e9f4",
    color: "#fff",
    borderRadius: 5,
    boxShadow:
      "0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4",
  },
  "& span": { position: "absolute", display: "block" },
  "& span:nth-child(1)": {
    top: 0,
    left: "-100%",
    width: "100%",
    height: 2,
    background: "linear-gradient(90deg, transparent, #03e9f4)",
    animation: "btnAnim1 1s linear infinite",
  },
  "@keyframes btnAnim1": {
    "0%": { left: "-100%" },
    "50%, 100%": { left: "100%" },
  },
  "& span:nth-child(2)": {
    top: "-100%",
    right: 0,
    width: 2,
    height: "100%",
    background: "linear-gradient(180deg, transparent, #03e9f4)",
    animation: "btnAnim2 1s linear infinite",
    animationDelay: "0.25s",
  },
  "@keyframes btnAnim2": {
    "0%": { top: "-100%" },
    "50%, 100%": { top: "100%" },
  },
  "& span:nth-child(3)": {
    bottom: 0,
    right: "-100%",
    width: "100%",
    height: 2,
    background: "linear-gradient(270deg, transparent, #03e9f4)",
    animation: "btnAnim3 1s linear infinite",
    animationDelay: "0.5s",
  },
  "@keyframes btnAnim3": {
    "0%": { right: "-100%" },
    "50%, 100%": { right: "100%" },
  },
  "& span:nth-child(4)": {
    bottom: "-100%",
    left: 0,
    width: 2,
    height: "100%",
    background: "linear-gradient(360deg, transparent, #03e9f4)",
    animation: "btnAnim4 1s linear infinite",
    animationDelay: "0.75s",
  },
  "@keyframes btnAnim4": {
    "0%": { bottom: "-100%" },
    "50%, 100%": { bottom: "100%" },
  },
});
